DISPLACEMENT_SCALE = [-0.25, 0.25]
SECANT_VELOCITY_SCALE = [-0.05, 0.05]
VELOCITY_SCALE = [-0.05, 0.05]
SCALE_DICT = {
    'displacement': DISPLACEMENT_SCALE,
    'secant_velocity': SECANT_VELOCITY_SCALE,
    'velocity': VELOCITY_SCALE,
}
