name: opera-disp-tms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - ruff
  - mypy
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  # For Running
  - gdal
  # FIXME check if boto3 S3 stub functonality is fixed in the future
  - boto3<1.36.0
  - asf_search
  - shapely
  - pyproj
  - h5py
  - h5netcdf
  - xarray
  - rioxarray
  - numba
  - s3fs
  - cachetools
