name: opera-disp-tms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  - moto[s3]
  # For Running
  - gdal
  - boto3>=1.36.0
  - h5py
  - h5netcdf
  - xarray
  - rioxarray
  - numba
  - s3fs
  - cachetools
  - numpy
  - requests
  - pip:
    - -r requirements-static.txt
