name: opera-disp-tms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For Running
  - gdal
  - boto3
  - asf_search
  - shapely
  - pyproj
  - h5py
  - h5netcdf
  - xarray
  - rioxarray
  - numba
  - s3fs
  - cachetools
